name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 0. Check out the repo
      - uses: actions/checkout@v4

      # 1. Install Nix (flakes already enabled)
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        # with:
        #   extra_nix_config: |
        #     experimental-features = nix-command flakes

      # 2. (Optional) share /nix/store across runs for speed
      - uses: DeterminateSystems/magic-nix-cache-action@v3

      # 3. Build & run every flake check (pytest, formatting, etc.)
      # - name: Run flake checks
      #   run: nix flake check --print-build-logs

      # 4. Or call your dev-shell directly:
      # - run: nix develop .# --command pytest -q
      - run: nix develop --command pytest -q test_sysexit.py
